services:

  minecraft-bot:
    container_name: minecraft-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - bot_logs:/app/logs # New volume to store bot logs
    ports:
      - "25565:25565" # Maps container port 25565 to host port 25565
    stdin_open: true
    tty: true

volumes:
  bot_logs: # This defines a named volume
