services:

  minecraft-bot:
    container_name: minecraft-discord-bot
    build: .  
    env_file: 
      - .env
    volumes:
      - ./Server:/app/Server # Minecraft server file persists (Direct volume bind to PC dir)
      - bot_logs:/app/logs # New volume to store bot logs
    ports:
      - "25565:25565" # Maps container port 25565 to host port 25565
    stdin_open: true
    tty: true

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host  # Allows Playit to manage networking properly
    env_file:
      - .env
    environment:
      - SECRET_KEY=${PLAYIT_SECRET}  # Use Railway or .env variable
    stdin_open: true  # ✅ Keep stdin open to capture logs
    tty: true  # ✅ Enable interactive logging
    command: ["/usr/local/bin/playit", "run"]  # ✅ Run Playit in foreground

volumes:
  bot_logs: # This defines a named volume
