services:

  minecraft-bot:
    container_name: minecraft-discord-bot
    build: .      
    env_file:
      - .env
    volumes:
      - Server:/app/Server # Minecraft server file persists (Direct volume bind to PC dir)
      - bot_logs:/app/logs # New volume to store bot logs
    ports:
      - "25565:25565" # Maps container port 25565 to host port 25565
    stdin_open: true
    tty: true

volumes:
  bot_logs: # This defines a named volume
