services:

  minecraft-bot:
    container_name: minecraft-discord-bot
    build: .
    env_file:
      - .env
    volumes:
      - ../Server:/app/Server
    ports:
      - "25565:25565" # Maps container port 25565 to host port 25565
    stdin_open: true
    tty: true
