name: Run Java Tests

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
      
      - name: Build and run tests with Maven
        run: mvn -B clean test
